#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TTViewer_v0003.Droid.Resource", IsApplication=true)]

namespace TTViewer_v0003.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int red = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sample01 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sample02 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample03 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sample04 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample05 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample06 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample07 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sample08 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sample09 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sample10 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sample11 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sample12 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sample13 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sample14 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sample15 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int sample16 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int sample17 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int sample18 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sample19 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int sample20 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int sample21 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int sample22 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int sample23 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int sample24 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int sample25 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int sample26 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int sample27 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int sample28 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int sample29 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int sample30 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int sample31 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int sample32 = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomActionBarTheme = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int Mono_Android_Theme_Splash = 2130903042;
			
			// aapt resource value: 0x7f030001
			public const int MyActionBar = 2130903041;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
